# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers


class ATan2Options(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsATan2Options(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ATan2Options()
        x.Init(buf, n + offset)
        return x

    # ATan2Options
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)


def ATan2OptionsStart(builder): builder.StartObject(0)
def ATan2OptionsEnd(builder): return builder.EndObject()
