# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers


class SignOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSignOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SignOptions()
        x.Init(buf, n + offset)
        return x

    # SignOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)


def SignOptionsStart(builder): builder.StartObject(0)
def SignOptionsEnd(builder): return builder.EndObject()
