# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers


class UnsortedSegmentSumOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUnsortedSegmentSumOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnsortedSegmentSumOptions()
        x.Init(buf, n + offset)
        return x

    # UnsortedSegmentSumOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)


def UnsortedSegmentSumOptionsStart(builder): builder.StartObject(0)
def UnsortedSegmentSumOptionsEnd(builder): return builder.EndObject()
