# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers


class UnsortedSegmentProdOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUnsortedSegmentProdOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnsortedSegmentProdOptions()
        x.Init(buf, n + offset)
        return x

    # UnsortedSegmentProdOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)


def UnsortedSegmentProdOptionsStart(builder): builder.StartObject(0)
def UnsortedSegmentProdOptionsEnd(builder): return builder.EndObject()
