# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers


class UnsortedSegmentMaxOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUnsortedSegmentMaxOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnsortedSegmentMaxOptions()
        x.Init(buf, n + offset)
        return x

    # UnsortedSegmentMaxOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)


def UnsortedSegmentMaxOptionsStart(builder): builder.StartObject(0)
def UnsortedSegmentMaxOptionsEnd(builder): return builder.EndObject()
